### PR TITLE
MTV-80: Performance recommendations (kbase)

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/MTV-80

Turn [MTV 2.0 Scale & Performance](https://docs.google.com/document/d/11zXodYcykdtaUgjeAduutG4Ow--hqxje6hWUDZXBNlw/edit#) into a [Kbase article](https://access.redhat.com/articles/6242511) (not accessible because it is still a draft)

Preview: https://deploy-preview-185--forklift-documentation.netlify.app/documentation/performance/performance-recommendations/

### CODE REVIEW

**Comment by mordechai** [comment]
@apinnick 
My suggestions are:
- '_Fast, dedicated networks for the migration_' should include line about datastore speeds, migrations are bound by esx datatstore speed, then network.
- _Maximum recommended number of VMs per host_ section requires rewording see below[1]
- _Maximum recommended number of VMs per host_ table should use index small 2 also here as done in previous table indicating that '2 Exceeding this value does not improve performance.'
- In _Maximum number of concurrent disk transfers_ / _Migration Example_  would be good to include esx datastore read rate.
- consider slight rewording of '_The following table displays the improved performance with additional ESXi hosts_' to 'The following table displays the improved performance of migrating 50 VMs with additional ESXi hosts.
- Maximum number of concurrent disk transfers section looks really great with the table and sub indexes.




[1] Maximum recommended number of VMs per host
- here we want to talk about Maximum recommended number of concurent disk migrations.  The way its currently written is that its focused on VMs to Host aspect and this is not correct as we can have hundreds of vms per host, how many we migrate concurrently is what your table is showing.  Let me know if unclear.

**Comment by apinnick** [comment]
>     * '_Fast, dedicated networks for the migration_' should include line about datastore speeds, migrations are bound by esx datatstore speed, then network.

@mordechai  The performance document says this about datastore read speeds:

> Datastores read rates impact the total transfer times, it's important to ensure fast reads are possible from the esx datastore to the esx host.  Example in numbers: 800MB/s was the average read rate for vsphere endpoint, and 350-500MB/s on average for esx endpoint.  Speed of reads between endpoints are documented here:  (BZ 1957985)

There is a separate section about vSphere endpoint vs ESXi endpoint, including a table showing speed. I could add a line to the endpoint section about how the endpoints affect the datastore read speeds. I do not think it is necessary to repeat this section in the "fast network" recommendation when much of it is mentioned in the Endpoint section.

Re: max concurrent disk transfers/VMs -- yes, of course we mean concurrent migrations, not VMs existing on a host. It hadn't occurred to me that that point might be misunderstood. I will check each occurrence to make sure that we're only concerned about the migrating VMs/disks.

Everything else is clear.

**Comment by mordechai** [comment]
Reviewed and looks good.
Thank you @apinnick

**Comment by apinnick** [comment]
Thanks, @mordechai 
I have asked a couple writers to check it from a docs perspective. When they approve it, I will publish it on the Customer Portal and add a link to the Jira and close it.

**Comment by apinnick** [comment]
Closing PR. Article published: https://access.redhat.com/articles/6242511

**Pull request closed without merging**
